<script setup lang="ts">
import {
    Activity,
    AlertTriangle,
    Archive,
    ArrowLeftRight,
    Bell,
    Boxes,
    Building2,
    CheckSquare,
    Circle,
    CircleAlert,
    CircleCheck,
    CircleDashed,
    CircleDot,
    CircleSlash,
    CircleX,
    ClipboardCheck,
    Clock,
    Eye,
    FilePen,
    FilePlus,
    Flag,
    FolderKanban,
    GitBranch,
    GitFork,
    Hourglass,
    Info,
    OctagonAlert,
    Package,
    PackageCheck,
    PackageMinus,
    PackagePlus,
    Paperclip,
    Pause,
    PencilRuler,
    Play,
    Search,
    Settings,
    SignalHigh,
    SignalLow,
    SignalMedium,
    Siren,
    Sparkles,
    Split,
    SquarePlay,
    Stamp,
    TriangleAlert,
    Truck,
    User,
    UserCheck,
    Webhook,
    Zap,
} from '@lucide/vue';
import type { Component } from 'vue';
import { computed } from 'vue';

/**
 * Renders an icon named by the server (statuses, activity entries, search
 * results), so PHP never needs to know about the icon library.
 */
const props = defineProps<{ name: string }>();

const icons: Record<string, Component> = {
    activity: Activity,
    'alert-triangle': AlertTriangle,
    archive: Archive,
    'arrow-left-right': ArrowLeftRight,
    bell: Bell,
    boxes: Boxes,
    building: Building2,
    'check-square': CheckSquare,
    circle: Circle,
    'circle-alert': CircleAlert,
    'circle-check': CircleCheck,
    'circle-dashed': CircleDashed,
    'circle-dot': CircleDot,
    'circle-slash': CircleSlash,
    'circle-x': CircleX,
    'clipboard-check': ClipboardCheck,
    clock: Clock,
    eye: Eye,
    'file-pen': FilePen,
    'file-plus': FilePlus,
    flag: Flag,
    folder: FolderKanban,
    'git-branch': GitBranch,
    'git-fork': GitFork,
    hourglass: Hourglass,
    info: Info,
    'octagon-alert': OctagonAlert,
    package: Package,
    'package-check': PackageCheck,
    'package-minus': PackageMinus,
    'package-plus': PackagePlus,
    paperclip: Paperclip,
    pause: Pause,
    'pencil-ruler': PencilRuler,
    play: Play,
    search: Search,
    settings: Settings,
    'signal-high': SignalHigh,
    'signal-low': SignalLow,
    'signal-medium': SignalMedium,
    siren: Siren,
    sparkles: Sparkles,
    split: Split,
    'square-play': SquarePlay,
    stamp: Stamp,
    'triangle-alert': TriangleAlert,
    truck: Truck,
    user: User,
    'user-check': UserCheck,
    webhook: Webhook,
    zap: Zap,
};

const icon = computed(() => icons[props.name] ?? Activity);
</script>

<template>
    <component :is="icon" aria-hidden="true" />
</template>
